language: android

# Setup Android environment
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

cache:
  directories:
  - $HOME/.gradle

# Emulator Management: Create, Start and Wait
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y ivy
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean testDebugUnitTest connectedDebugAndroidTest

deploy:
  provider: script
  script: ./gradlew clean assembleRelease
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"

after_failure:
  - adb logcat -d
